storage_endpoint="DefaultEndpointsProtocol=https;AccountName=s653829458i;AccountKey=KQOr/41tYR56HEXuwXyR+OB2NyYhMtTXdXuPUAENON/PM7MLxhAdpU3taen83ic4YFeB79jyn9e+0WKHjiuTzw==;EndpointSuffix=core.windows.net"
eventhubns_endpoint="Endpoint=sb://event12843496ssssss.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=clHqVN3h0gox7553soxYH8BXgV8CU7TWaxQHvIrsnkE="
eventhub_namespace=""
eventhub_name="event1"
container_name="container1"
